### ISSUE TITLE
Trying to use vorto-dashboard with Bosch IoT platform

### ISSUE THREAD

**Issue by patrickse** [eclipse/vorto-examples#185]
Hi,

I´ve tried to use the vorto-dashboard with Bosch IoT. For some reason it fails during fetching the devices from my account. It looks like it´s missing the 'definition' property for displaying the devices on the website and fails with a blank/black screen.

That´s the error message on the Javascript Console

```
react-dom.production.min.js:4636 TypeError: Cannot read property 'some' of undefined
    at KpiCardTwoCol.jsx:67
    at Array.some (<anonymous>)
    at KpiCardTwoCol.jsx:66
    at Array.filter (<anonymous>)
    at t.value (KpiCardTwoCol.jsx:65)
    at Jo (react-dom.production.min.js:4241)
    at Xo (react-dom.production.min.js:4232)
    at Rs (react-dom.production.min.js:6671)
    at Al (react-dom.production.min.js:5648)
    at Nl (react-dom.production.min.js:5637)
```

I´ve just installed version
```
info "vorto-dashboard@0.5.0" has binaries:
   - vorto-dashboard
```

Hope someone can help.

**Comment by patrickse** [comment]
It looks like it´s related to missing feature->definitions. For some reason the Bosch IoT result does not provide these informations.

```json
    "features": {
      "temperature": {
        "properties": {
          "status": {
            "value": {
              "currentMeasured": 25.9
            }
          }
        }
      },
```

**Comment by aedelmann** [comment]
Yeah the Vorto dashboard expects all things to be specifying the definition property. As a handy tip, U can use the postman script generator for your Vorto model that automatically creates the correct Thing structure in ditto / things via the provisioning API

**Comment by aedelmann** [comment]
Hi @patrickse 
We have fixed your issue that the dashboard should not break anymore if you have features with missing definitions. Can you please verify with the latest version on npm ?

**Comment by patrickse** [comment]
Just tried yesterday and everything is working fine. Instead of a crashing dashboard I receive the json representation of the property. Thanks 👍
