### ISSUE TITLE
Vorto Normalizer uses relative instead of absolute directory mapping path.

### ISSUE THREAD

**Issue by patrickse** [eclipse/vorto-examples#208]
@tmtnckff according to https://github.com/eclipse/vorto-examples/blob/master/vorto-middleware/Readme.md#running-the-vorto-normalizer-service the environment variable for `mapping_spec_dir` should be absolute. But due to the implementation of `System.getProperty("user.dir")` in the passed part needs to be relative. 

https://github.com/eclipse/vorto-examples/blob/de39125eca0fb347855ea00e01127b37703b6731/vorto-middleware/middleware-service/src/main/java/org/eclipse/vorto/middleware/config/MappingSpecsConfiguration.java#L55

**Comment by tmtnckff** [comment]
Hey, @patrickse thank you for the advice. As stated in the [documentation](https://github.com/eclipse/vorto-examples/blob/master/vorto-middleware/Readme.md#running-the-vorto-normalizer-service), the environment variable `mapping_spec_dir` is an additional mentioning of the folder name path inside the docker container.

The docker volume parameter ` -v /absolute_local_directory_path:/directory_path_on_image` actually defines two paths separated by a colon: On the one side an absolute path for the local directory (left side) and on the other side a non absolute folder name (right side) which has to be the same value as set in `mapping_spec_dir` . Therefore, `mapping_spec_dir` doesn't need to be absolute, as it is only accessed in respect to the Spring Boot application running in the docker container. I will update the documentation today, as this seems a bit confusing.

**Comment by patrickse** [comment]
Ah ok I got it. From the docker-perspective you´re totally right. I am starting the application without docker on my machine and therefor there´s no docker volume mounting and this leads to some strange folder resolution like `/d/dev/iot/vorto-examples/vorto-middleware/middleware-service/d/dev/iot/specs` when run the normalizer with `mapping_spec_dir=/d/dev/iot/specs`.

As far as I can see your `Dockerfile` is not specificing a `WORKDIR` and therefor the user.dir is pointed to `/`. If you would just use

```java
 File externalDirectory = new File(mappingSpecDirectory); 
```

there would be no problem with running it inside docker or without docker.

Just an idea...

**Comment by aedelmann** [comment]
Hi @patrickse 
Should be fixed. Can you verify ?

**Comment by patrickse** [comment]
@aedelmann as long as the only intense is to run it inside docker... everything is fine. 

But I still think it´s redundant to define `System.getProperty("user.dir")+ mappingSpecDirectory` as `System.getProperty("user.dir")` resolves to `/` in docker because no WORKDIR is configured. In a none Docker environment things would be easier when leaving out the user.dir variable.

**Comment by aedelmann** [comment]
@patrickse 
Yeah, we intend to support both with and without docker. In any case, we removed the user.dir.
