### ISSUE TITLE
Specific url that links to the device details page in Vorto dashboard

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto-examples#85]
It should be possible to copy and paste a link of the device details page

**Comment by timgrossmann** [comment]
In order to make the Dashboard more "sharable", it would be nice to be able to share links with devices mentioned in the URL.

e.g. http://vorto-dashboard.eu-central-1.elasticbeanstalk.com/#/devicedashboard/com.bosch.si.sgp:16-01903

This will require changes on the React router.
